services:

  flask-app:
    build: .
    container_name: flask_app_container
    ports:
      - "8080:8080"
    networks:
      - e-comm-network
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    depends_on:
      - e-comm-db

  e-comm-db:
    image: postgres:latest
    restart: always
    container_name: e-comm-db
    platform: linux/${ARCH:-amd64}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U SYS"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    env_file:
      - docker-compose-local.env
    ports:
      - '5432:5432'
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - ./sql:/sql
      - e-comm-volume:/var/lib/postgresql/data/
    networks:
      - e-comm-network



networks:
  e-comm-network:

volumes:
  e-comm-volume: