apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQVEzRUdTUFc2UjZUVlBETEc=
  AWS_SECRET_ACCESS_KEY: UHRMVndZdzcxbU41bFd5NkFNeTU0NkJUSVd5cmdkRXFiN3V2c2NvTw==
